
-- Create system_email_templates table
CREATE TABLE public.system_email_templates (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  template_key TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  subject TEXT NOT NULL,
  html_content TEXT NOT NULL,
  text_content TEXT,
  variables JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create system_sms_templates table
CREATE TABLE public.system_sms_templates (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  template_key TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  content TEXT NOT NULL,
  variables JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.system_email_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_sms_templates ENABLE ROW LEVEL SECURITY;

-- RLS Policies for email templates
CREATE POLICY "Admins can manage email templates" ON public.system_email_templates
  FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "System can read email templates" ON public.system_email_templates
  FOR SELECT USING (true);

-- RLS Policies for SMS templates
CREATE POLICY "Admins can manage SMS templates" ON public.system_sms_templates
  FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "System can read SMS templates" ON public.system_sms_templates
  FOR SELECT USING (true);

-- Create updated_at trigger function if not exists
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_email_templates_updated_at
  BEFORE UPDATE ON public.system_email_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_sms_templates_updated_at
  BEFORE UPDATE ON public.system_sms_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Insert default email templates
INSERT INTO public.system_email_templates (template_key, category, name, description, subject, html_content, variables) VALUES

-- Welcome Category
('welcome_new_user', 'welcome', 'Welcome New User', 'Sent when a new user registers', 'Welcome to {app_name}! 🎉', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.logo{max-height:50px;margin-bottom:20px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.subtitle{color:#666;font-size:16px;margin-top:8px}.content{margin:30px 0}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600;margin:20px 0}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><h1 class="title">Welcome to {app_name}!</h1><p class="subtitle">We''re excited to have you on board</p></div><div class="content"><p>Hi {user_name},</p><p>Thank you for joining {app_name}! Your account has been successfully created and you''re ready to get started.</p><p>Here''s what you can do next:</p><ul><li>Complete your profile setup</li><li>Explore our features</li><li>Connect your social accounts</li></ul><center><a href="{dashboard_url}" class="btn">Go to Dashboard</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "app_name", "description": "Application name"}, {"name": "dashboard_url", "description": "Dashboard URL"}, {"name": "current_year", "description": "Current year"}]'),

('welcome_trial_started', 'welcome', 'Trial Started', 'Sent when user starts a free trial', 'Your {trial_days}-Day Free Trial Has Started!', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.badge{display:inline-block;background:linear-gradient(135deg,#10b981,#059669);color:#fff;padding:8px 16px;border-radius:20px;font-size:14px;font-weight:600;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.highlight-box{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:20px;margin:20px 0}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><span class="badge">🎁 FREE TRIAL</span><h1 class="title">Your Trial Has Started!</h1></div><div class="content"><p>Hi {user_name},</p><p>Great news! Your {trial_days}-day free trial of {plan_name} is now active.</p><div class="highlight-box"><strong>Trial Details:</strong><br>Plan: {plan_name}<br>Started: {start_date}<br>Expires: {end_date}</div><p>During your trial, you''ll have full access to all {plan_name} features. Make the most of it!</p><center><a href="{dashboard_url}" class="btn">Start Exploring</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "trial_days", "description": "Number of trial days"}, {"name": "plan_name", "description": "Trial plan name"}, {"name": "start_date", "description": "Trial start date"}, {"name": "end_date", "description": "Trial end date"}, {"name": "dashboard_url", "description": "Dashboard URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

-- Auth Category
('email_verification', 'auth', 'Email Verification', 'Sent to verify user email address', 'Verify Your Email Address', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.otp-box{background:#f8fafc;border:2px dashed #cbd5e1;border-radius:8px;padding:20px;text-align:center;margin:25px 0}.otp-code{font-size:32px;font-weight:700;letter-spacing:8px;color:#1a1a1a}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">✉️</div><h1 class="title">Verify Your Email</h1></div><div class="content"><p>Hi {user_name},</p><p>Please verify your email address by clicking the button below or using the verification code:</p><div class="otp-box"><div class="otp-code">{verification_code}</div><p style="margin:10px 0 0;color:#666;font-size:14px">Code expires in {expiry_minutes} minutes</p></div><center><a href="{verification_url}" class="btn">Verify Email</a></center><p style="color:#666;font-size:14px;margin-top:25px">If you didn''t create an account, please ignore this email.</p></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "verification_code", "description": "Verification code"}, {"name": "verification_url", "description": "Verification link URL"}, {"name": "expiry_minutes", "description": "Code expiry in minutes"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('password_reset', 'auth', 'Password Reset', 'Sent when user requests password reset', 'Reset Your Password', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.warning-box{background:#fef3c7;border:1px solid #fcd34d;border-radius:8px;padding:15px;margin:20px 0;font-size:14px}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">🔐</div><h1 class="title">Reset Your Password</h1></div><div class="content"><p>Hi {user_name},</p><p>We received a request to reset your password. Click the button below to create a new password:</p><center><a href="{reset_url}" class="btn">Reset Password</a></center><div class="warning-box">⚠️ This link will expire in {expiry_hours} hours. If you didn''t request this, please ignore this email or contact support.</div><p style="color:#666;font-size:14px">For security, this request was received from:<br>IP: {ip_address}<br>Time: {request_time}</p></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "reset_url", "description": "Password reset URL"}, {"name": "expiry_hours", "description": "Link expiry in hours"}, {"name": "ip_address", "description": "Request IP address"}, {"name": "request_time", "description": "Request timestamp"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('password_changed', 'auth', 'Password Changed', 'Sent when password is successfully changed', 'Your Password Has Been Changed', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.success-box{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:15px;margin:20px 0}.btn{display:inline-block;background:#ef4444;color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">✅</div><h1 class="title">Password Changed</h1></div><div class="content"><p>Hi {user_name},</p><div class="success-box">Your password was successfully changed on {change_time}.</div><p>If you made this change, no further action is needed.</p><p><strong>Didn''t make this change?</strong></p><p>Your account may have been compromised. Please take immediate action:</p><center><a href="{support_url}" class="btn">Contact Support</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "change_time", "description": "Password change timestamp"}, {"name": "support_url", "description": "Support page URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('two_factor_code', 'auth', 'Two-Factor Authentication Code', 'Sent for 2FA verification', 'Your Login Code: {code}', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.code-box{background:linear-gradient(135deg,#6366f1,#8b5cf6);border-radius:12px;padding:30px;text-align:center;margin:25px 0}.code{font-size:40px;font-weight:700;letter-spacing:12px;color:#fff}.expiry{color:rgba(255,255,255,.8);font-size:14px;margin-top:10px}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">🔒</div><h1 class="title">Your Login Code</h1></div><div class="content"><p>Hi {user_name},</p><p>Use this code to complete your sign-in:</p><div class="code-box"><div class="code">{code}</div><div class="expiry">Expires in {expiry_minutes} minutes</div></div><p style="color:#666;font-size:14px">If you didn''t try to sign in, someone may be trying to access your account. Please change your password immediately.</p></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "code", "description": "2FA code"}, {"name": "expiry_minutes", "description": "Code expiry in minutes"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

-- Subscription Category
('subscription_activated', 'subscription', 'Subscription Activated', 'Sent when subscription is activated', 'Your {plan_name} Subscription is Active! 🎉', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.badge{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;padding:8px 16px;border-radius:20px;font-size:14px;font-weight:600;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.plan-card{background:linear-gradient(135deg,#1e1b4b,#312e81);border-radius:12px;padding:25px;color:#fff;margin:20px 0}.plan-name{font-size:24px;font-weight:700;margin-bottom:10px}.plan-price{font-size:18px;opacity:.9}.features{background:#f8fafc;border-radius:8px;padding:20px;margin:20px 0}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><span class="badge">✨ SUBSCRIPTION ACTIVE</span><h1 class="title">Welcome to {plan_name}!</h1></div><div class="content"><p>Hi {user_name},</p><p>Your subscription has been successfully activated. Here are your plan details:</p><div class="plan-card"><div class="plan-name">{plan_name}</div><div class="plan-price">{amount} / {billing_cycle}</div></div><div class="features"><strong>What''s included:</strong><ul>{features_list}</ul><p><strong>Reply Credits:</strong> {reply_quota} / month</p><p><strong>Next Billing:</strong> {next_billing_date}</p></div><center><a href="{dashboard_url}" class="btn">Go to Dashboard</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "plan_name", "description": "Subscription plan name"}, {"name": "amount", "description": "Subscription amount"}, {"name": "billing_cycle", "description": "Billing cycle (monthly/yearly)"}, {"name": "features_list", "description": "HTML list of features"}, {"name": "reply_quota", "description": "Monthly reply quota"}, {"name": "next_billing_date", "description": "Next billing date"}, {"name": "dashboard_url", "description": "Dashboard URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('subscription_renewed', 'subscription', 'Subscription Renewed', 'Sent when subscription auto-renews', 'Your Subscription Has Been Renewed', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.info-box{background:#f8fafc;border-radius:8px;padding:20px;margin:20px 0}.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #e2e8f0}.row:last-child{border-bottom:none}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">🔄</div><h1 class="title">Subscription Renewed</h1></div><div class="content"><p>Hi {user_name},</p><p>Your {plan_name} subscription has been successfully renewed.</p><div class="info-box"><div class="row"><span>Plan</span><strong>{plan_name}</strong></div><div class="row"><span>Amount</span><strong>{amount}</strong></div><div class="row"><span>Period</span><strong>{period_start} - {period_end}</strong></div><div class="row"><span>Reply Credits Reset</span><strong>{reply_quota}</strong></div></div><center><a href="{invoice_url}" class="btn">View Invoice</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "plan_name", "description": "Plan name"}, {"name": "amount", "description": "Amount charged"}, {"name": "period_start", "description": "Period start date"}, {"name": "period_end", "description": "Period end date"}, {"name": "reply_quota", "description": "Reply quota"}, {"name": "invoice_url", "description": "Invoice URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('subscription_cancelled', 'subscription', 'Subscription Cancelled', 'Sent when subscription is cancelled', 'Your Subscription Has Been Cancelled', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.warning-box{background:#fef3c7;border:1px solid #fcd34d;border-radius:8px;padding:20px;margin:20px 0}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.btn-outline{display:inline-block;border:2px solid #6366f1;color:#6366f1!important;text-decoration:none;padding:12px 30px;border-radius:8px;font-weight:600;margin-left:10px}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">😢</div><h1 class="title">We''re Sorry to See You Go</h1></div><div class="content"><p>Hi {user_name},</p><p>Your {plan_name} subscription has been cancelled as requested.</p><div class="warning-box"><strong>Important:</strong> Your access will continue until <strong>{access_end_date}</strong>. After this date, you''ll be moved to the Free plan.</div><p>We''d love to know why you''re leaving. Your feedback helps us improve.</p><center><a href="{resubscribe_url}" class="btn">Resubscribe</a><a href="{feedback_url}" class="btn-outline">Give Feedback</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "plan_name", "description": "Plan name"}, {"name": "access_end_date", "description": "Access end date"}, {"name": "resubscribe_url", "description": "Resubscribe URL"}, {"name": "feedback_url", "description": "Feedback URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('subscription_expiring', 'subscription', 'Subscription Expiring Soon', 'Sent before subscription expires', 'Your Subscription Expires in {days_remaining} Days', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.countdown{background:linear-gradient(135deg,#f59e0b,#d97706);color:#fff;display:inline-block;padding:15px 30px;border-radius:50px;font-size:24px;font-weight:700;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="countdown">{days_remaining} days left</div><h1 class="title">Your Subscription is Expiring</h1></div><div class="content"><p>Hi {user_name},</p><p>Your {plan_name} subscription will expire on <strong>{expiry_date}</strong>.</p><p>Don''t lose access to your premium features! Renew now to continue enjoying:</p><ul>{features_list}</ul><center><a href="{renew_url}" class="btn">Renew Subscription</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "plan_name", "description": "Plan name"}, {"name": "days_remaining", "description": "Days until expiry"}, {"name": "expiry_date", "description": "Expiry date"}, {"name": "features_list", "description": "HTML list of features"}, {"name": "renew_url", "description": "Renewal URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

-- Payment Category
('payment_success', 'payment', 'Payment Successful', 'Sent when payment is successful', 'Payment Received - Thank You!', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.receipt{background:#f8fafc;border-radius:8px;padding:20px;margin:20px 0}.row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #e2e8f0}.row:last-child{border-bottom:none;font-weight:700;font-size:18px}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">✅</div><h1 class="title">Payment Successful!</h1></div><div class="content"><p>Hi {user_name},</p><p>Thank you for your payment. Here''s your receipt:</p><div class="receipt"><div class="row"><span>Transaction ID</span><span>{transaction_id}</span></div><div class="row"><span>Description</span><span>{description}</span></div><div class="row"><span>Payment Method</span><span>{payment_method}</span></div><div class="row"><span>Date</span><span>{payment_date}</span></div><div class="row"><span>Amount Paid</span><span>{amount}</span></div></div><center><a href="{invoice_url}" class="btn">Download Invoice</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "transaction_id", "description": "Transaction ID"}, {"name": "description", "description": "Payment description"}, {"name": "payment_method", "description": "Payment method"}, {"name": "payment_date", "description": "Payment date"}, {"name": "amount", "description": "Amount paid"}, {"name": "invoice_url", "description": "Invoice URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('payment_failed', 'payment', 'Payment Failed', 'Sent when payment fails', 'Payment Failed - Action Required', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#ef4444;margin:0}.content{margin:30px 0}.error-box{background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:20px;margin:20px 0}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">❌</div><h1 class="title">Payment Failed</h1></div><div class="content"><p>Hi {user_name},</p><p>We were unable to process your payment.</p><div class="error-box"><strong>Error:</strong> {error_message}<br><strong>Amount:</strong> {amount}<br><strong>Date:</strong> {attempt_date}</div><p>Please update your payment method to continue using {app_name}.</p><center><a href="{update_payment_url}" class="btn">Update Payment Method</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "error_message", "description": "Error message"}, {"name": "amount", "description": "Amount"}, {"name": "attempt_date", "description": "Attempt date"}, {"name": "update_payment_url", "description": "Update payment URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('invoice_sent', 'payment', 'Invoice', 'Invoice email to customers', 'Invoice #{invoice_number} from {store_name}', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{border-bottom:2px solid #e2e8f0;padding-bottom:20px;margin-bottom:20px}.logo{max-height:40px}.invoice-title{font-size:24px;font-weight:700;color:#1a1a1a;margin:10px 0 0}.invoice-meta{color:#666;font-size:14px}.content{margin:20px 0}.items-table{width:100%;border-collapse:collapse;margin:20px 0}.items-table th,.items-table td{padding:12px;text-align:left;border-bottom:1px solid #e2e8f0}.items-table th{background:#f8fafc;font-weight:600}.total-row{font-weight:700;font-size:18px}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><h1 class="invoice-title">INVOICE</h1><p class="invoice-meta">#{invoice_number} • {invoice_date}</p></div><div class="content"><p><strong>Bill To:</strong><br>{customer_name}<br>{customer_phone}</p><table class="items-table"><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>{items_html}<tr class="total-row"><td colspan="3">Subtotal</td><td>{subtotal}</td></tr><tr><td colspan="3">Shipping</td><td>{shipping}</td></tr><tr><td colspan="3">Discount</td><td>-{discount}</td></tr><tr class="total-row"><td colspan="3">Total</td><td>{total}</td></tr></table><center><a href="{payment_url}" class="btn">Pay Now</a></center></div><div class="footer"><p>{store_name}<br>{store_phone}</p></div></div></div></body></html>', '[{"name": "invoice_number", "description": "Invoice number"}, {"name": "invoice_date", "description": "Invoice date"}, {"name": "customer_name", "description": "Customer name"}, {"name": "customer_phone", "description": "Customer phone"}, {"name": "items_html", "description": "HTML table rows for items"}, {"name": "subtotal", "description": "Subtotal amount"}, {"name": "shipping", "description": "Shipping charge"}, {"name": "discount", "description": "Discount amount"}, {"name": "total", "description": "Total amount"}, {"name": "payment_url", "description": "Payment URL"}, {"name": "store_name", "description": "Store name"}, {"name": "store_phone", "description": "Store phone"}]'),

-- Notification Category
('quota_warning', 'notification', 'Quota Warning', 'Sent when quota usage is high', '⚠️ You''ve Used {usage_percent}% of Your Reply Quota', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#f59e0b;margin:0}.content{margin:30px 0}.progress-bar{background:#e2e8f0;border-radius:10px;height:20px;overflow:hidden;margin:20px 0}.progress-fill{background:linear-gradient(90deg,#f59e0b,#ef4444);height:100%;border-radius:10px}.stats{display:flex;justify-content:space-around;margin:20px 0}.stat{text-align:center}.stat-value{font-size:24px;font-weight:700;color:#1a1a1a}.stat-label{font-size:14px;color:#666}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">⚠️</div><h1 class="title">Quota Warning</h1></div><div class="content"><p>Hi {user_name},</p><p>You''ve used a significant portion of your monthly reply quota:</p><div class="progress-bar"><div class="progress-fill" style="width:{usage_percent}%"></div></div><div class="stats"><div class="stat"><div class="stat-value">{replies_used}</div><div class="stat-label">Used</div></div><div class="stat"><div class="stat-value">{replies_remaining}</div><div class="stat-label">Remaining</div></div><div class="stat"><div class="stat-value">{reset_days}</div><div class="stat-label">Days to Reset</div></div></div><p>Need more replies? Upgrade your plan or purchase a top-up pack.</p><center><a href="{upgrade_url}" class="btn">Upgrade Plan</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "usage_percent", "description": "Usage percentage"}, {"name": "replies_used", "description": "Replies used"}, {"name": "replies_remaining", "description": "Replies remaining"}, {"name": "reset_days", "description": "Days until quota reset"}, {"name": "upgrade_url", "description": "Upgrade URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('new_feature', 'notification', 'New Feature Announcement', 'Sent when new feature is released', '🎉 New Feature: {feature_name}', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.badge{display:inline-block;background:linear-gradient(135deg,#10b981,#059669);color:#fff;padding:8px 16px;border-radius:20px;font-size:14px;font-weight:600;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.feature-image{width:100%;border-radius:8px;margin:20px 0}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><span class="badge">🆕 NEW FEATURE</span><h1 class="title">{feature_name}</h1></div><div class="content"><p>Hi {user_name},</p><p>We''re excited to announce a new feature:</p><p>{feature_description}</p><center><a href="{feature_url}" class="btn">Try It Now</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "feature_name", "description": "Feature name"}, {"name": "feature_description", "description": "Feature description"}, {"name": "feature_url", "description": "Feature URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

-- Account Category
('account_suspended', 'account', 'Account Suspended', 'Sent when account is suspended', 'Your Account Has Been Suspended', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#ef4444;margin:0}.content{margin:30px 0}.reason-box{background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:20px;margin:20px 0}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">🚫</div><h1 class="title">Account Suspended</h1></div><div class="content"><p>Hi {user_name},</p><p>Your account has been suspended due to the following reason:</p><div class="reason-box">{suspension_reason}</div><p>If you believe this is an error, please contact our support team.</p><center><a href="{appeal_url}" class="btn">Appeal Suspension</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "suspension_reason", "description": "Reason for suspension"}, {"name": "appeal_url", "description": "Appeal URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('account_reactivated', 'account', 'Account Reactivated', 'Sent when suspended account is reactivated', 'Your Account Has Been Reactivated! 🎉', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#10b981;margin:0}.content{margin:30px 0}.success-box{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:20px;margin:20px 0}.btn{display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff!important;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">✅</div><h1 class="title">Account Reactivated!</h1></div><div class="content"><p>Hi {user_name},</p><div class="success-box">Good news! Your account has been reactivated and you now have full access to all features.</div><p>We''re glad to have you back. If you have any questions, our support team is here to help.</p><center><a href="{dashboard_url}" class="btn">Go to Dashboard</a></center></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "dashboard_url", "description": "Dashboard URL"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]'),

('account_deleted', 'account', 'Account Deletion Confirmation', 'Sent when account is deleted', 'Your Account Has Been Deleted', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#333;margin:0;padding:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;padding:20px}.card{background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.08)}.header{text-align:center;margin-bottom:30px}.icon{font-size:48px;margin-bottom:15px}.title{font-size:28px;font-weight:700;color:#1a1a1a;margin:0}.content{margin:30px 0}.info-box{background:#f8fafc;border-radius:8px;padding:20px;margin:20px 0}.footer{text-align:center;color:#999;font-size:12px;margin-top:30px;padding-top:20px;border-top:1px solid #eee}</style></head><body><div class="container"><div class="card"><div class="header"><div class="icon">👋</div><h1 class="title">Goodbye</h1></div><div class="content"><p>Hi {user_name},</p><p>Your account and all associated data have been permanently deleted as requested.</p><div class="info-box"><strong>What was deleted:</strong><ul><li>Your profile information</li><li>Connected social accounts</li><li>Chatbot flows and automations</li><li>Message history</li></ul></div><p>We''re sorry to see you go. If you ever want to come back, you''re always welcome to create a new account.</p><p>Thank you for being a part of {app_name}.</p></div><div class="footer"><p>© {current_year} {app_name}. All rights reserved.</p></div></div></div></body></html>', '[{"name": "user_name", "description": "User''s full name"}, {"name": "app_name", "description": "Application name"}, {"name": "current_year", "description": "Current year"}]');

-- Insert default SMS templates
INSERT INTO public.system_sms_templates (template_key, category, name, description, content, variables) VALUES

-- Auth Category
('otp_verification', 'auth', 'OTP Verification', 'Phone number verification OTP', 'Your {app_name} verification code is: {otp_code}. Valid for {expiry_minutes} minutes. Do not share this code.', '[{"name": "app_name", "description": "Application name"}, {"name": "otp_code", "description": "OTP code"}, {"name": "expiry_minutes", "description": "Code expiry in minutes"}]'),

('login_code', 'auth', 'Login Code', 'Two-factor authentication code', 'Your {app_name} login code: {code}. Expires in {expiry_minutes} min. If you didn''t request this, ignore it.', '[{"name": "app_name", "description": "Application name"}, {"name": "code", "description": "Login code"}, {"name": "expiry_minutes", "description": "Code expiry in minutes"}]'),

('password_reset_sms', 'auth', 'Password Reset SMS', 'Password reset notification via SMS', 'Your {app_name} password reset code: {reset_code}. Valid for {expiry_minutes} min. Don''t share this code.', '[{"name": "app_name", "description": "Application name"}, {"name": "reset_code", "description": "Reset code"}, {"name": "expiry_minutes", "description": "Code expiry in minutes"}]'),

-- Notification Category
('quota_warning_sms', 'notification', 'Quota Warning SMS', 'Low quota warning via SMS', 'Warning: You''ve used {usage_percent}% of your {app_name} reply quota. {replies_remaining} replies left. Upgrade: {upgrade_url}', '[{"name": "app_name", "description": "Application name"}, {"name": "usage_percent", "description": "Usage percentage"}, {"name": "replies_remaining", "description": "Remaining replies"}, {"name": "upgrade_url", "description": "Upgrade URL"}]'),

-- Payment Category
('payment_success_sms', 'payment', 'Payment Success SMS', 'Payment confirmation via SMS', 'Payment of {amount} received for {app_name}. Transaction ID: {transaction_id}. Thank you!', '[{"name": "app_name", "description": "Application name"}, {"name": "amount", "description": "Payment amount"}, {"name": "transaction_id", "description": "Transaction ID"}]'),

('payment_failed_sms', 'payment', 'Payment Failed SMS', 'Payment failure notification', 'Your {app_name} payment of {amount} failed. Please update your payment method: {update_url}', '[{"name": "app_name", "description": "Application name"}, {"name": "amount", "description": "Payment amount"}, {"name": "update_url", "description": "Update payment URL"}]'),

-- Subscription Category
('subscription_expiring_sms', 'subscription', 'Subscription Expiring SMS', 'Subscription expiry reminder', 'Your {app_name} {plan_name} expires in {days_remaining} days. Renew now: {renew_url}', '[{"name": "app_name", "description": "Application name"}, {"name": "plan_name", "description": "Plan name"}, {"name": "days_remaining", "description": "Days remaining"}, {"name": "renew_url", "description": "Renewal URL"}]'),

-- Welcome Category
('welcome_sms', 'welcome', 'Welcome SMS', 'Welcome message for new users', 'Welcome to {app_name}, {user_name}! Your account is ready. Get started: {dashboard_url}', '[{"name": "app_name", "description": "Application name"}, {"name": "user_name", "description": "User name"}, {"name": "dashboard_url", "description": "Dashboard URL"}]');
